package com.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.price
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.produce_date
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private Date produceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.address
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.category_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_id
     *
     * @return the value of tb_goods.goods_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_id
     *
     * @param goodsId the value for tb_goods.goods_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.price
     *
     * @return the value of tb_goods.price
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.price
     *
     * @param price the value for tb_goods.price
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.produce_date
     *
     * @return the value of tb_goods.produce_date
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.produce_date
     *
     * @param produceDate the value for tb_goods.produce_date
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.address
     *
     * @return the value of tb_goods.address
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.address
     *
     * @param address the value for tb_goods.address
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.category_id
     *
     * @return the value of tb_goods.category_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.category_id
     *
     * @param categoryId the value for tb_goods.category_id
     *
     * @mbggenerated Fri Aug 19 17:52:11 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}